name: Dependency Updates

on:
  schedule:
    - cron: '0 8 * * 1'  # Weekly on Mondays at 8 AM UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'

    - name: Check for dependency updates
      id: updates
      run: |
        # Check for outdated packages
        npm outdated --json > outdated.json || true
        
        if [ -s outdated.json ]; then
          echo "updates-available=true" >> $GITHUB_OUTPUT
          echo "📦 Dependency updates available:"
          cat outdated.json | jq -r 'to_entries[] | "- \(.key): \(.value.current) → \(.value.wanted)"'
        else
          echo "updates-available=false" >> $GITHUB_OUTPUT
          echo "✅ All dependencies are up to date"
        fi

    - name: Update dependencies
      if: steps.updates.outputs.updates-available == 'true'
      run: |
        # Update dependencies
        npm update
        
        # Update dev dependencies
        npm update --save-dev

    - name: Run tests after update
      if: steps.updates.outputs.updates-available == 'true'
      run: |
        npm ci
        npm test
        npm run build

    - name: Create Pull Request
      if: steps.updates.outputs.updates-available == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: '📦 Automated dependency updates'
        body: |
          This PR contains automated dependency updates.
          
          ## Changes
          - Updated npm dependencies to latest compatible versions
          - All tests pass with updated dependencies
          
          ## Verification
          - ✅ Tests pass
          - ✅ Build succeeds
          - ✅ Security audit clean
          
          Auto-generated by GitHub Actions 🤖
        branch: dependency-updates
        delete-branch: true
        assignees: ${{ github.repository_owner }}
        reviewers: ${{ github.repository_owner }}

    - name: Security audit
      if: steps.updates.outputs.updates-available == 'true'
      run: |
        npm audit --audit-level moderate